package com.bayram.promarksaha;
import android.content.*;import android.graphics.*;import android.view.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
public class FieldMapView extends View{
 public interface Listener{void onMapLongPress(double lat,double lon);}
 private GnssFix fix;private SurveyPoint a,b,target;private final ArrayList<SurveyPoint> profileMarks=new ArrayList<>();private Listener listener;private final Paint p=new Paint(3);private final Map<String,Bitmap> tiles=new ConcurrentHashMap<>();private final Set<String> loading=ConcurrentHashMap.newKeySet();private final ExecutorService io=Executors.newFixedThreadPool(6);private int zoom=18,mode=0;private double centerLat=Double.NaN,centerLon=Double.NaN,scaleAcc=1;private boolean followFix=true;private final GestureDetector gestures;private final ScaleGestureDetector scales;
 public FieldMapView(Context c){super(c);p.setAntiAlias(true);setBackgroundColor(0xff202020);gestures=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){public boolean onDown(MotionEvent e){return true;}public boolean onScroll(MotionEvent e1,MotionEvent e2,float dx,float dy){pan(dx,dy);return true;}public void onLongPress(MotionEvent e){double[] ll=screenToLatLon(e.getX(),e.getY());if(listener!=null)listener.onMapLongPress(ll[0],ll[1]);}});scales=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){scaleAcc*=d.getScaleFactor();if(scaleAcc>1.22){changeZoom(zoom+1,d.getFocusX(),d.getFocusY());scaleAcc=1;}else if(scaleAcc<0.82){changeZoom(zoom-1,d.getFocusX(),d.getFocusY());scaleAcc=1;}return true;}public void onScaleEnd(ScaleGestureDetector d){scaleAcc=1;}});}
 public void setListener(Listener l){listener=l;}public void setFix(GnssFix f){fix=f;if(Double.isNaN(centerLat)||followFix){centerLat=f.lat;centerLon=f.lon;}invalidate();}public void setLine(SurveyPoint x,SurveyPoint y){a=x;b=y;invalidate();}public void setTarget(SurveyPoint t){target=t;invalidate();}public void setProfileMarks(List<SurveyPoint> list){profileMarks.clear();if(list!=null)profileMarks.addAll(list);invalidate();}public void clearMarks(){a=b=target=null;profileMarks.clear();invalidate();}public void recenter(){followFix=true;if(fix!=null){centerLat=fix.lat;centerLon=fix.lon;}invalidate();}public String cycleMode(){mode=(mode+1)%3;invalidate();return modeName();}public String modeName(){return mode==0?"UYDU":mode==1?"HIBRIT":"YOL";}public int zoom(){return zoom;}
 public boolean onTouchEvent(MotionEvent e){boolean s=scales.onTouchEvent(e),g=gestures.onTouchEvent(e);return s||g||super.onTouchEvent(e);}
 protected void onDraw(Canvas c){super.onDraw(c);if(Double.isNaN(centerLat)){p.setColor(Color.LTGRAY);p.setTextSize(24);p.setTextAlign(Paint.Align.CENTER);c.drawText("KONUM BEKLENIYOR",getWidth()/2f,getHeight()/2f,p);return;}drawTiles(c);if(profileMarks.size()>1){p.setColor(0xff00e5ff);p.setStrokeWidth(4);for(int i=1;i<profileMarks.size();i++){PointF p0=screen(profileMarks.get(i-1).lat,profileMarks.get(i-1).lon),p1=screen(profileMarks.get(i).lat,profileMarks.get(i).lon);c.drawLine(p0.x,p0.y,p1.x,p1.y,p);}}for(SurveyPoint m:profileMarks)drawPoint(c,m,m.name.startsWith("ND")?0xffffd600:0xff00e5ff,m.name);if(a!=null)drawPoint(c,a,0xffffa000,"P1");if(b!=null)drawPoint(c,b,0xffffa000,"P2");if(a!=null&&b!=null){PointF pa=screen(a.lat,a.lon),pb=screen(b.lat,b.lon);p.setColor(0xffff8a00);p.setStrokeWidth(6);c.drawLine(pa.x,pa.y,pb.x,pb.y,p);}if(target!=null){PointF pt=screen(target.lat,target.lon);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(0xff00e676);c.drawCircle(pt.x,pt.y,24,p);c.drawLine(pt.x-31,pt.y,pt.x+31,pt.y,p);c.drawLine(pt.x,pt.y-31,pt.x,pt.y+31,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(18);c.drawText("HEDEF",pt.x,pt.y-33,p);}if(fix!=null&&!Double.isNaN(fix.lat)){PointF me=screen(fix.lat,fix.lon);p.setColor(0xffe53935);p.setStyle(Paint.Style.FILL);c.drawCircle(me.x,me.y,12,p);p.setColor(Color.WHITE);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);c.drawCircle(me.x,me.y,17,p);p.setStyle(Paint.Style.FILL);}p.setTextAlign(Paint.Align.LEFT);p.setTextSize(18);p.setColor(Color.WHITE);c.drawText(modeName()+"  Z"+zoom+(followFix?"  KONUMA KILITLI":"  SERBEST"),12,getHeight()-16,p);}
 private void drawPoint(Canvas c,SurveyPoint s,int color,String label){PointF pt=screen(s.lat,s.lon);p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawCircle(pt.x,pt.y,10,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(17);p.setColor(Color.WHITE);c.drawText(label,pt.x+13,pt.y-10,p);}
 private void pan(float dx,float dy){if(Double.isNaN(centerLat))return;followFix=false;double[] w=world(centerLat,centerLon,zoom);double[] ll=unworld(w[0]+dx,w[1]+dy,zoom);centerLat=ll[0];centerLon=ll[1];invalidate();}
 private void changeZoom(int nz,float fx,float fy){nz=Math.max(3,Math.min(20,nz));if(nz==zoom||Double.isNaN(centerLat))return;double[] anchor=screenToLatLon(fx,fy);zoom=nz;double[] aw=world(anchor[0],anchor[1],zoom);double cx=aw[0]-(fx-getWidth()/2f),cy=aw[1]-(fy-getHeight()/2f);double[] ll=unworld(cx,cy,zoom);centerLat=ll[0];centerLon=ll[1];followFix=false;invalidate();}
 private double[] screenToLatLon(float sx,float sy){double[] cw=world(centerLat,centerLon,zoom);return unworld(cw[0]+sx-getWidth()/2f,cw[1]+sy-getHeight()/2f,zoom);}
 private void drawTiles(Canvas c){double[] w=world(centerLat,centerLon,zoom);int ts=256,cx=(int)Math.floor(w[0]/ts),cy=(int)Math.floor(w[1]/ts);int rx=Math.max(2,getWidth()/ts/2+2),ry=Math.max(2,getHeight()/ts/2+2);for(int dx=-rx;dx<=rx;dx++)for(int dy=-ry;dy<=ry;dy++){int tx=cx+dx,ty=cy+dy;float l=(float)(getWidth()/2+(tx*ts-w[0])),t=(float)(getHeight()/2+(ty*ts-w[1]));if(mode==2)drawLayer(c,"road",roadUrl(zoom,tx,ty),zoom,tx,ty,l,t);else{drawLayer(c,"sat",satUrl(zoom,tx,ty),zoom,tx,ty,l,t);if(mode==1){drawLayer(c,"transport",transportUrl(zoom,tx,ty),zoom,tx,ty,l,t);drawLayer(c,"labels",labelsUrl(zoom,tx,ty),zoom,tx,ty,l,t);}}}}
 private void drawLayer(Canvas c,String layer,String url,int z,int x,int y,float l,float t){String k=layer+"_"+z+"_"+x+"_"+y;Bitmap bm=tiles.get(k);if(bm!=null)c.drawBitmap(bm,l,t,p);else load(k,layer,url);}
 private void load(String k,String layer,String url){if(!loading.add(k))return;io.submit(()->{try{File d=new File(getContext().getCacheDir(),"maps_"+layer);d.mkdirs();File f=new File(d,k+".img");Bitmap bm=f.exists()?BitmapFactory.decodeFile(f.getAbsolutePath()):null;if(bm==null){HttpURLConnection h=(HttpURLConnection)new URL(url).openConnection();h.setRequestProperty("User-Agent","ProMarkSaha/0.4");h.setConnectTimeout(3500);h.setReadTimeout(5000);h.setInstanceFollowRedirects(true);if(h.getResponseCode()/100==2){try(InputStream in=h.getInputStream();FileOutputStream out=new FileOutputStream(f)){byte[] q=new byte[16384];int n;while((n=in.read(q))>0)out.write(q,0,n);}bm=BitmapFactory.decodeFile(f.getAbsolutePath());}}if(bm!=null){tiles.put(k,bm);postInvalidate();}}catch(Exception ignored){}finally{loading.remove(k);}});}
 private String satUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/"+z+"/"+y+"/"+x;}private String transportUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/"+z+"/"+y+"/"+x;}private String labelsUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/"+z+"/"+y+"/"+x;}private String roadUrl(int z,int x,int y){return "https://tile.openstreetmap.org/"+z+"/"+x+"/"+y+".png";}
 private PointF screen(double lat,double lon){double[] aa=world(lat,lon,zoom),bb=world(centerLat,centerLon,zoom);return new PointF((float)(getWidth()/2+aa[0]-bb[0]),(float)(getHeight()/2+aa[1]-bb[1]));}
 private static double[] world(double lat,double lon,int z){double n=Math.pow(2,z)*256.0,x=(lon+180)/360*n,s=Math.sin(Math.toRadians(Math.max(-85.0511,Math.min(85.0511,lat)))),y=(0.5-Math.log((1+s)/(1-s))/(4*Math.PI))*n;return new double[]{x,y};}private static double[] unworld(double x,double y,int z){double n=Math.pow(2,z)*256.0,lon=x/n*360.0-180.0,a=Math.PI-2*Math.PI*y/n,lat=Math.toDegrees(Math.atan(Math.sinh(a)));return new double[]{lat,lon};}
}
