package com.bayram.promarksaha;
import android.content.*;import android.graphics.*;import android.view.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
public class FieldMapView extends View{
 private GnssFix fix;private SurveyPoint a,b;private final Paint p=new Paint(3);private final Map<String,Bitmap> tiles=new ConcurrentHashMap<>();private final Set<String> loading=ConcurrentHashMap.newKeySet();private final ExecutorService io=Executors.newFixedThreadPool(6);private int zoom=18,mode=0;
 public FieldMapView(Context c){super(c);p.setAntiAlias(true);setBackgroundColor(0xff202020);}public void setFix(GnssFix f){fix=f;invalidate();}public void setLine(SurveyPoint x,SurveyPoint y){a=x;b=y;invalidate();}
 public String cycleMode(){mode=(mode+1)%3;invalidate();return modeName();}public String modeName(){return mode==0?"UYDU":mode==1?"HIBRIT":"YOL";}
 protected void onDraw(Canvas c){super.onDraw(c);if(fix==null||Double.isNaN(fix.lat)){p.setColor(Color.LTGRAY);p.setTextSize(24);p.setTextAlign(Paint.Align.CENTER);c.drawText("KONUM BEKLENIYOR",getWidth()/2f,getHeight()/2f,p);return;}drawTiles(c,fix.lat,fix.lon);if(a!=null&&b!=null){PointF pa=screen(a.lat,a.lon,fix.lat,fix.lon),pb=screen(b.lat,b.lon,fix.lat,fix.lon);p.setColor(0xffff8a00);p.setStrokeWidth(7);c.drawLine(pa.x,pa.y,pb.x,pb.y,p);}float mx=getWidth()/2f,my=getHeight()/2f;p.setColor(0xffe53935);c.drawCircle(mx,my,13,p);p.setColor(Color.WHITE);p.setStrokeWidth(3);c.drawLine(mx-22,my,mx+22,my,p);c.drawLine(mx,my-22,mx,my+22,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(20);p.setColor(Color.WHITE);c.drawText(modeName(),12,getHeight()-16,p);}
 private void drawTiles(Canvas c,double lat,double lon){double[] w=world(lat,lon,zoom);int ts=256,cx=(int)Math.floor(w[0]/ts),cy=(int)Math.floor(w[1]/ts);for(int dx=-2;dx<=2;dx++)for(int dy=-2;dy<=2;dy++){int tx=cx+dx,ty=cy+dy;float l=(float)(getWidth()/2+(tx*ts-w[0])),t=(float)(getHeight()/2+(ty*ts-w[1]));if(mode==2){drawLayer(c,"road",roadUrl(zoom,tx,ty),zoom,tx,ty,l,t);}else{drawLayer(c,"sat",satUrl(zoom,tx,ty),zoom,tx,ty,l,t);if(mode==1){drawLayer(c,"transport",transportUrl(zoom,tx,ty),zoom,tx,ty,l,t);drawLayer(c,"labels",labelsUrl(zoom,tx,ty),zoom,tx,ty,l,t);}}}}
 private void drawLayer(Canvas c,String layer,String url,int z,int x,int y,float l,float t){String k=layer+"_"+z+"_"+x+"_"+y;Bitmap bm=tiles.get(k);if(bm!=null)c.drawBitmap(bm,l,t,p);else load(k,layer,url);}
 private void load(String k,String layer,String url){if(!loading.add(k))return;io.submit(()->{try{File d=new File(getContext().getCacheDir(),"maps_"+layer);d.mkdirs();File f=new File(d,k+".img");Bitmap bm=null;if(f.exists())bm=BitmapFactory.decodeFile(f.getAbsolutePath());if(bm==null){HttpURLConnection h=(HttpURLConnection)new URL(url).openConnection();h.setRequestProperty("User-Agent","ProMarkSaha/0.3");h.setConnectTimeout(3500);h.setReadTimeout(5000);h.setInstanceFollowRedirects(true);if(h.getResponseCode()/100==2){try(InputStream in=h.getInputStream();FileOutputStream out=new FileOutputStream(f)){byte[] q=new byte[16384];int n;while((n=in.read(q))>0)out.write(q,0,n);}bm=BitmapFactory.decodeFile(f.getAbsolutePath());}}if(bm!=null){tiles.put(k,bm);postInvalidate();}}catch(Exception ignored){}finally{loading.remove(k);}});}
 private String satUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/"+z+"/"+y+"/"+x;}
 private String transportUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/"+z+"/"+y+"/"+x;}
 private String labelsUrl(int z,int x,int y){return "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/"+z+"/"+y+"/"+x;}
 private String roadUrl(int z,int x,int y){return "https://tile.openstreetmap.org/"+z+"/"+x+"/"+y+".png";}
 private PointF screen(double lat,double lon,double clat,double clon){double[] aa=world(lat,lon,zoom),bb=world(clat,clon,zoom);return new PointF((float)(getWidth()/2+aa[0]-bb[0]),(float)(getHeight()/2+aa[1]-bb[1]));}
 private static double[] world(double lat,double lon,int z){double n=Math.pow(2,z)*256.0,x=(lon+180)/360*n,s=Math.sin(Math.toRadians(Math.max(-85.0511,Math.min(85.0511,lat)))),y=(0.5-Math.log((1+s)/(1-s))/(4*Math.PI))*n;return new double[]{x,y};}
}
