package com.bayram.promarksaha;
import android.Manifest;import android.annotation.SuppressLint;import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class MainActivity extends Activity {private TextView state,sol,coord,nav,q;private FieldMapView map;private BluetoothGnss bt;private final NmeaParser parser=new NmeaParser();private GnssFix last;private SurveyPoint p1,p2,profileLast;private final ArrayList<SurveyPoint> pts=new ArrayList<>();private final ArrayList<GnssFix> cap=new ArrayList<>();private boolean capturing=false,profile=false;private long capStart;private String pendingType="NOKTA";private static final int REQ_EXPORT=91;
 public void onCreate(Bundle b){super.onCreate(b);bt=new BluetoothGnss(this);build();if(Build.VERSION.SDK_INT>=31)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},50);}private TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(10,7,10,7);return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setOnClickListener(v->act(((Button)v).getText().toString()));return b;}
 private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(0xff101316);LinearLayout t=new LinearLayout(this);state=tv("ProMark: BAGLI DEGIL",14);sol=tv("NO FIX",18);t.addView(state,new LinearLayout.LayoutParams(0,-2,1));t.addView(sol);r.addView(t);q=tv("Uydu: -   H: -   V: -",14);coord=tv("X: -  Y: -  Z: -  TM: -",14);nav=tv("Hat secilmedi",16);nav.setBackgroundColor(0xff252b30);r.addView(q);r.addView(coord);r.addView(nav);map=new FieldMapView(this);r.addView(map,new LinearLayout.LayoutParams(-1,0,1));GridLayout g=new GridLayout(this);g.setColumnCount(4);for(String s:new String[]{"BAGLAN","NOKTA AL","P1 AL","P2 AL","PROFIL","ENGEL","HEDEFE GIT","XYZ"}){Button x=btn(s);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);g.addView(x,lp);}r.addView(g);setContentView(r);}
 private void act(String s){if(s.contains("BAGLAN"))choose();else if(s.contains("NOKTA"))startCap("NOKTA");else if(s.contains("P1"))line(true);else if(s.contains("P2"))line(false);else if(s.contains("PROFIL")){profile=!profile;profileLast=null;toast(profile?"Profil acik: her 2 m XYZ kayit":"Profil kapali");}else if(s.contains("ENGEL"))startCap("ENGEL");else if(s.contains("HEDEFE"))toast(p2==null?"Once P2 alin":"P2 hedef aktif");else if(s.equals("XYZ"))exportXYZ();}
 @SuppressLint("MissingPermission")private void choose(){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_SCAN},50);return;}List<BluetoothDevice>d=bt.paired();if(d.isEmpty()){toast("Android Bluetooth ayarindan ProMark ile eslestirin");return;}String[] n=new String[d.size()];for(int i=0;i<d.size();i++)n[i]=d.get(i).getName()+"\n"+d.get(i).getAddress();new AlertDialog.Builder(this).setTitle("GNSS cihazi").setItems(n,(x,w)->connect(d.get(w))).show();}
 @SuppressLint("MissingPermission")private void connect(BluetoothDevice d){bt.connect(d,new BluetoothGnss.Listener(){public void onLine(String l){GnssFix f=parser.parse(l);if(f!=null&&f.valid())runOnUiThread(()->onFix(f));}public void onState(String s){runOnUiThread(()->state.setText("ProMark: "+s));}});}
 private void onFix(GnssFix f){last=f;map.setFix(f);GeoMath.TM t=GeoMath.toTM3(f.lat,f.lon);sol.setText(f.solution());sol.setTextColor(f.quality==4?0xff38d469:f.quality==2?0xff54b8ff:f.quality==5?0xffffc247:0xffff8a00);q.setText(String.format(Locale.US,"Uydu %d  H %s  V %s  HDOP %s",f.satellites,fmt(f.hSigma),fmt(f.vSigma),fmt(f.hdop)));coord.setText(String.format(Locale.US,"X %.3f  Y %.3f  Z %.3f  TM%d",t.xNorthing,t.yEasting,f.alt,t.cm));nav(t,f);if(profile)autoProfile(t,f);if(capturing){cap.add(f);if(cap.size()>=12||System.currentTimeMillis()-capStart>4000)finishCap();}}
 private void nav(GeoMath.TM c,GnssFix f){if(p1==null||p2==null){nav.setText("Hat secilmedi | X=Kuzey Y=Dogu");return;}GeoMath.LineNav n=GeoMath.lineNav(p1.x,p1.y,p2.x,p2.y,c.xNorthing,c.yEasting);double h=!Double.isNaN(f.courseDeg)&&f.speedKmh>0.7?f.courseDeg:n.bearing,d=GeoMath.angleDiff(n.bearing,h);String side=n.crossTrack<0.08?"HAT UZERINDESIN":String.format(Locale.US,"%.2f m %s",n.crossTrack,n.rightOfLine?"SAGDASIN":"SOLDASIN"),steer=n.crossTrack<0.08?"DUZ GIT":n.rightOfLine?"SOLA GEL":"SAGA GEL",rot=Math.abs(d)<8?"":String.format(Locale.US," | %s %.0f°",d>0?"SAGA DON":"SOLA DON",Math.abs(d));nav.setText(String.format(Locale.US,"%s | %s | Kalan %.2f m%s",side,steer,n.remaining,rot));nav.setBackgroundColor(n.crossTrack<0.08?0xff176b36:n.crossTrack<0.5?0xff665115:0xff6b2424);}
 private void line(boolean first){if(last==null){toast("Konum yok");return;}GeoMath.TM t=GeoMath.toTM3(last.lat,last.lon);SurveyPoint p=new SurveyPoint();p.name=first?"P1":"P2";p.lat=last.lat;p.lon=last.lon;p.x=t.xNorthing;p.y=t.yEasting;p.z=last.alt;p.cm=t.cm;if(first)p1=p;else p2=p;map.setLine(p1,p2);toast(p.name+" alindi");}
 private void startCap(String type){if(last==null){toast("ProMark konumu yok");return;}pendingType=type;cap.clear();capturing=true;capStart=System.currentTimeMillis();toast("Olcum basladi");}
 private void finishCap(){capturing=false;if(cap.isEmpty())return;int cm=GeoMath.autoCentralMeridian(cap.get(cap.size()-1).lon),n=0;double sx=0,sy=0,sz=0,lat=0,lon=0;for(GnssFix f:cap){if(!f.valid())continue;GeoMath.TM t=GeoMath.toTM3(f.lat,f.lon,cm);sx+=t.xNorthing;sy+=t.yEasting;sz+=f.alt;lat+=f.lat;lon+=f.lon;n++;}if(n==0)return;SurveyPoint p=new SurveyPoint();p.name=String.format(Locale.US,"N%03d",pts.size()+1);p.type=pendingType;p.x=sx/n;p.y=sy/n;p.z=sz/n;p.lat=lat/n;p.lon=lon/n;p.cm=cm;p.solution=last.solution();EditText e=new EditText(this);e.setHint("Aciklama");new AlertDialog.Builder(this).setTitle(p.name+" "+p.type).setMessage(String.format(Locale.US,"X %.3f\nY %.3f\nZ %.3f\nTM%d %s",p.x,p.y,p.z,p.cm,p.solution)).setView(e).setPositiveButton("KAYDET",(d,w)->{p.description=e.getText().toString();pts.add(p);toast("Kaydedildi");}).setNegativeButton("IPTAL",null).show();}
 private void autoProfile(GeoMath.TM t,GnssFix f){if(p1==null||p2==null)return;GeoMath.LineNav n=GeoMath.lineNav(p1.x,p1.y,p2.x,p2.y,t.xNorthing,t.yEasting);if(n.crossTrack>1.5)return;if(profileLast!=null&&GeoMath.distance(profileLast.x,profileLast.y,t.xNorthing,t.yEasting)<2)return;SurveyPoint p=new SurveyPoint();p.name="PR"+(pts.size()+1);p.type="PROFIL";p.x=t.xNorthing;p.y=t.yEasting;p.z=f.alt;p.lat=f.lat;p.lon=f.lon;p.cm=t.cm;p.solution=f.solution();pts.add(p);profileLast=p;}
 private void exportXYZ(){if(pts.isEmpty()){toast("Kayit yok");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"ProMark_XYZ_"+System.currentTimeMillis()+".txt");startActivityForResult(i,REQ_EXPORT);}protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ_EXPORT&&c==RESULT_OK&&d!=null&&d.getData()!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){for(SurveyPoint p:pts)o.write(String.format(Locale.US,"%.3f\t%.3f\t%.3f\n",p.x,p.y,p.z).getBytes(StandardCharsets.UTF_8));toast("XYZ kaydedildi");}catch(Exception e){toast("Hata: "+e.getMessage());}}
 private String fmt(double v){return Double.isNaN(v)?"-":String.format(Locale.US,"%.2f",v);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}protected void onDestroy(){super.onDestroy();bt.disconnect();}}
