package com.bayram.promarksaha;
import android.Manifest;import android.annotation.SuppressLint;import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.location.*;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class MainActivity extends Activity{
 private TextView state,sol,coord,nav,q;private Button mapBtn;private FieldMapView map;private BluetoothGnss bt;private LocationManager lm;private final NmeaParser parser=new NmeaParser();private GnssFix last;private SurveyPoint p1,p2,profileLast;private final ArrayList<SurveyPoint> pts=new ArrayList<>(),dummy=new ArrayList<>();private final ArrayList<GnssFix> cap=new ArrayList<>();private boolean capturing=false,profile=false;private long capStart,promarkLastMs=0;private String pendingType="NOKTA",source="Tablet GPS";private static final int REQ_EXPORT=91,REQ_BT_ON=92,REQ_PERM=50;private BluetoothDevice pendingBond;private AlertDialog scanDlg;private ArrayAdapter<String> scanAdapter;private final LinkedHashMap<String,BluetoothDevice> scanned=new LinkedHashMap<>();
 private final LocationListener deviceListener=loc->{if(System.currentTimeMillis()-promarkLastMs<3000)return;GnssFix f=new GnssFix();f.timeMs=System.currentTimeMillis();f.lat=loc.getLatitude();f.lon=loc.getLongitude();f.alt=loc.hasAltitude()?loc.getAltitude():Double.NaN;f.quality=1;f.hSigma=loc.hasAccuracy()?loc.getAccuracy():Double.NaN;if(Build.VERSION.SDK_INT>=26&&loc.hasVerticalAccuracy())f.vSigma=loc.getVerticalAccuracyMeters();if(loc.hasSpeed())f.speedKmh=loc.getSpeed()*3.6;if(loc.hasBearing())f.courseDeg=loc.getBearing();onFix(f,"Tablet GPS");};
 private final BroadcastReceiver btReceiver=new BroadcastReceiver(){@SuppressLint("MissingPermission")public void onReceive(Context c,Intent i){String a=i.getAction();BluetoothDevice d=i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);if(d==null)return;if(BluetoothDevice.ACTION_FOUND.equals(a)){String key=d.getAddress();if(!scanned.containsKey(key)){scanned.put(key,d);String n=d.getName();scanAdapter.add((n==null?"Adsiz cihaz":n)+"\n"+key+(d.getBondState()==BluetoothDevice.BOND_BONDED?"  ✓ Eslesmis":""));scanAdapter.notifyDataSetChanged();}}else if(BluetoothDevice.ACTION_BOND_STATE_CHANGED.equals(a)&&pendingBond!=null&&pendingBond.getAddress().equals(d.getAddress())&&d.getBondState()==BluetoothDevice.BOND_BONDED){pendingBond=null;if(scanDlg!=null)scanDlg.dismiss();toast("Eslesme tamamlandi, baglaniyor");connect(d);}}};
 public void onCreate(Bundle b){super.onCreate(b);bt=new BluetoothGnss(this);lm=(LocationManager)getSystemService(LOCATION_SERVICE);build();IntentFilter f=new IntentFilter();f.addAction(BluetoothDevice.ACTION_FOUND);f.addAction(BluetoothDevice.ACTION_BOND_STATE_CHANGED);if(Build.VERSION.SDK_INT>=33)registerReceiver(btReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(btReceiver,f);requestPermissionsAll();}
 private void requestPermissionsAll(){ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=31){if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_SCAN);}if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ_PERM);else startDeviceGps();}
 @SuppressLint("MissingPermission")private void startDeviceGps(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,800,0.1f,deviceListener);Location l=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l!=null)deviceListener.onLocationChanged(l);}catch(Exception e){state.setText("Tablet GPS kullanilamiyor");}}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_PERM)startDeviceGps();}
 private TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(10,6,10,6);return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setOnClickListener(v->act(((Button)v).getText().toString()));return b;}
 private void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(0xff101316);LinearLayout t=new LinearLayout(this);state=tv("KAYNAK: Tablet GPS",14);sol=tv("GPS BEKLENIYOR",17);t.addView(state,new LinearLayout.LayoutParams(0,-2,1));t.addView(sol);r.addView(t);q=tv("Uydu: -   H: -   V: -",14);coord=tv("X: -  Y: -  Z: -  TM: -",14);nav=tv("Hat secilmedi",15);nav.setBackgroundColor(0xff252b30);r.addView(q);r.addView(coord);r.addView(nav);map=new FieldMapView(this);r.addView(map,new LinearLayout.LayoutParams(-1,0,1));GridLayout g=new GridLayout(this);g.setColumnCount(3);String[] names={"BLUETOOTH","HARITA: UYDU","NOKTA AL","P1 AL","P2 AL","PROFIL","ENGEL","HEDEFE GIT","XYZ"};for(String s:names){Button x=btn(s);if(s.startsWith("HARITA"))mapBtn=x;GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);g.addView(x,lp);}r.addView(g);setContentView(r);}
 private void act(String s){if(s.contains("BLUETOOTH"))choose();else if(s.startsWith("HARITA")){String m=map.cycleMode();mapBtn.setText("HARITA: "+m);}else if(s.contains("NOKTA"))startCap("NOKTA");else if(s.contains("P1"))line(true);else if(s.contains("P2"))line(false);else if(s.contains("PROFIL")){profile=!profile;profileLast=null;toast(profile?"Profil acik: her 2 m kayit":"Profil kapali");}else if(s.contains("ENGEL"))startCap("ENGEL");else if(s.contains("HEDEFE"))toast(p2==null?"Once P2 alin":"P2 hedef aktif");else if(s.equals("XYZ"))exportXYZ();}
 @SuppressLint("MissingPermission")private void choose(){requestPermissionsAll();BluetoothAdapter a=bt.adapter();if(a==null){toast("Bu cihazda Bluetooth yok, tablet GPS ile devam");return;}if(!a.isEnabled()){startActivityForResult(new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE),REQ_BT_ON);return;}List<BluetoothDevice>d=bt.paired();ArrayList<String> rows=new ArrayList<>();for(BluetoothDevice x:d)rows.add("✓ "+safeName(x)+"\n"+x.getAddress());rows.add("🔎 YENI CIHAZ TARA");rows.add("⚙ BLUETOOTH AYARLARI");new AlertDialog.Builder(this).setTitle("ProMark / GNSS Bluetooth").setItems(rows.toArray(new String[0]),(x,w)->{if(w<d.size())connect(d.get(w));else if(w==d.size())scanDevices();else startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));}).setNegativeButton("KAPAT",null).show();}
 @SuppressLint("MissingPermission")private void scanDevices(){BluetoothAdapter a=bt.adapter();if(a==null||!a.isEnabled())return;scanned.clear();scanAdapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,new ArrayList<>());ListView list=new ListView(this);list.setAdapter(scanAdapter);scanDlg=new AlertDialog.Builder(this).setTitle("GNSS cihazlari taraniyor...").setView(list).setPositiveButton("YENIDEN TARA",null).setNegativeButton("KAPAT",null).create();scanDlg.setOnShowListener(z->scanDlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{scanned.clear();scanAdapter.clear();bt.startDiscovery();}));list.setOnItemClickListener((p,v,pos,id)->{BluetoothDevice d=new ArrayList<>(scanned.values()).get(pos);bt.cancelDiscovery();if(d.getBondState()==BluetoothDevice.BOND_BONDED){scanDlg.dismiss();connect(d);}else{pendingBond=d;state.setText("ProMark eslestiriliyor");if(!d.createBond()){pendingBond=null;toast("Eslesme baslatilamadi");}}});scanDlg.setOnDismissListener(z->bt.cancelDiscovery());scanDlg.show();bt.startDiscovery();}
 @SuppressLint("MissingPermission")private String safeName(BluetoothDevice d){String n=d.getName();return n==null?"Adsiz cihaz":n;}
 @SuppressLint("MissingPermission")private void connect(BluetoothDevice d){state.setText("ProMark baglaniyor: "+safeName(d));bt.connect(d,new BluetoothGnss.Listener(){public void onLine(String l){GnssFix f=parser.parse(l);if(f!=null&&f.valid())runOnUiThread(()->{promarkLastMs=System.currentTimeMillis();String src=(f.quality==2||f.quality==4||f.quality==5)?"CORS/ProMark":"ProMark GPS";onFix(f,src);});}public void onState(String s){runOnUiThread(()->{if(System.currentTimeMillis()-promarkLastMs>3000)state.setText("ProMark: "+s+" | Tablet GPS yedek");});}});}
 private void onFix(GnssFix f,String src){last=f;source=src;map.setFix(f);GeoMath.TM t=GeoMath.toTM3(f.lat,f.lon);state.setText("KAYNAK: "+src);sol.setText(src.equals("Tablet GPS")?"TABLET GPS":f.solution());sol.setTextColor(f.quality==4?0xff38d469:f.quality==2?0xff54b8ff:f.quality==5?0xffffc247:src.equals("Tablet GPS")?0xfff2d35c:0xffff8a00);q.setText(String.format(Locale.US,"H %s m  V %s m  HDOP %s",fmt(f.hSigma),fmt(f.vSigma),fmt(f.hdop)));coord.setText(String.format(Locale.US,"X %.3f  Y %.3f  Z %.3f  TM%d",t.xNorthing,t.yEasting,f.alt,t.cm));nav(t,f);if(profile)autoProfile(t,f);if(capturing){cap.add(f);if(cap.size()>=12||System.currentTimeMillis()-capStart>4000)finishCap();}}
 private void nav(GeoMath.TM c,GnssFix f){if(p1==null||p2==null){nav.setText("Hat secilmedi | X=Kuzey Y=Dogu");return;}GeoMath.LineNav n=GeoMath.lineNav(p1.x,p1.y,p2.x,p2.y,c.xNorthing,c.yEasting);double h=!Double.isNaN(f.courseDeg)&&f.speedKmh>0.7?f.courseDeg:n.bearing,d=GeoMath.angleDiff(n.bearing,h);String side=n.crossTrack<0.08?"HAT UZERINDESIN":String.format(Locale.US,"%.2f m %s",n.crossTrack,n.rightOfLine?"SAGDASIN":"SOLDASIN"),steer=n.crossTrack<0.08?"DUZ GIT":n.rightOfLine?"SOLA GEL":"SAGA GEL",rot=Math.abs(d)<8?"":String.format(Locale.US," | %s %.0f°",d>0?"SAGA DON":"SOLA DON",Math.abs(d));nav.setText(String.format(Locale.US,"%s | %s | Kalan %.2f m%s",side,steer,n.remaining,rot));nav.setBackgroundColor(n.crossTrack<0.08?0xff176b36:n.crossTrack<0.5?0xff665115:0xff6b2424);}
 private void line(boolean first){if(last==null){toast("Konum yok");return;}GeoMath.TM t=GeoMath.toTM3(last.lat,last.lon);SurveyPoint p=new SurveyPoint();p.name=first?"P1":"P2";p.lat=last.lat;p.lon=last.lon;p.x=t.xNorthing;p.y=t.yEasting;p.z=last.alt;p.cm=t.cm;p.solution=source;if(first)p1=p;else p2=p;map.setLine(p1,p2);toast(p.name+" alindi - "+source);}
 private void startCap(String type){if(last==null){toast("Konum bekleniyor");return;}pendingType=type;cap.clear();capturing=true;capStart=System.currentTimeMillis();toast("Olcum basladi - "+source);}
 private void finishCap(){capturing=false;if(cap.isEmpty())return;int cm=GeoMath.autoCentralMeridian(cap.get(cap.size()-1).lon),n=0;double sx=0,sy=0,sz=0,lat=0,lon=0;for(GnssFix f:cap){if(!f.valid())continue;GeoMath.TM t=GeoMath.toTM3(f.lat,f.lon,cm);sx+=t.xNorthing;sy+=t.yEasting;sz+=f.alt;lat+=f.lat;lon+=f.lon;n++;}if(n==0)return;SurveyPoint p=new SurveyPoint();p.name=String.format(Locale.US,"N%03d",pts.size()+1);p.type=pendingType;p.x=sx/n;p.y=sy/n;p.z=sz/n;p.lat=lat/n;p.lon=lon/n;p.cm=cm;p.solution=source;EditText e=new EditText(this);e.setHint("Aciklama");new AlertDialog.Builder(this).setTitle(p.name+" "+p.type).setMessage(String.format(Locale.US,"%s\nX %.3f\nY %.3f\nZ %.3f\nTM%d",source,p.x,p.y,p.z,p.cm)).setView(e).setPositiveButton("KAYDET",(d,w)->{p.description=e.getText().toString();pts.add(p);toast("Kaydedildi");}).setNegativeButton("IPTAL",null).show();}
 private void autoProfile(GeoMath.TM t,GnssFix f){if(p1==null||p2==null)return;GeoMath.LineNav n=GeoMath.lineNav(p1.x,p1.y,p2.x,p2.y,t.xNorthing,t.yEasting);if(n.crossTrack>1.5)return;if(profileLast!=null&&GeoMath.distance(profileLast.x,profileLast.y,t.xNorthing,t.yEasting)<2)return;SurveyPoint p=new SurveyPoint();p.name="PR"+(pts.size()+1);p.type="PROFIL";p.x=t.xNorthing;p.y=t.yEasting;p.z=f.alt;p.lat=f.lat;p.lon=f.lon;p.cm=t.cm;p.solution=source;pts.add(p);profileLast=p;}
 private void exportXYZ(){if(pts.isEmpty()){toast("Kayit yok");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"ProMark_XYZ_"+System.currentTimeMillis()+".txt");startActivityForResult(i,REQ_EXPORT);}protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ_BT_ON&&c==RESULT_OK){choose();return;}if(r==REQ_EXPORT&&c==RESULT_OK&&d!=null&&d.getData()!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){for(SurveyPoint p:pts)o.write(String.format(Locale.US,"%.3f\t%.3f\t%.3f\n",p.x,p.y,p.z).getBytes(StandardCharsets.UTF_8));toast("XYZ kaydedildi");}catch(Exception e){toast("Hata: "+e.getMessage());}}
 private String fmt(double v){return Double.isNaN(v)?"-":String.format(Locale.US,"%.2f",v);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}protected void onDestroy(){super.onDestroy();try{unregisterReceiver(btReceiver);}catch(Exception ignored){}try{lm.removeUpdates(deviceListener);}catch(Exception ignored){}bt.disconnect();}
}
